In [1]:
import numpy as np
from autodiff import Tensor

In [2]:
x = Tensor([[1,2,3],[-9,-8,7]],dtype=np.float32,requires_grad=True)
y = Tensor(-2,dtype=np.float32,requires_grad=True)

In [3]:
w1 = Tensor([[1,5,6]],dtype=np.float32,requires_grad=True)
w2 = Tensor([[-2,-4]],dtype=np.float32,requires_grad=True)

In [4]:
z = -x + y
z = z.dot(w1.T)
z = w2.dot(z)

In [5]:
z

Tensor([[174.]],name=dot_<tensor_3>_<dot_<add_<neg_<tensor_0>_4>_<tensor_1>_5>_<T_<tensor_2>_6>_7>_8,grad_fn=<DotBackward0>)

In [6]:
z.backward()

In [7]:
x

Tensor([[ 1.  2.  3.]
 [-9. -8.  7.]],name=tensor_0,requires_grad=True)

In [8]:
y

Tensor(-2.0,name=tensor_1,requires_grad=True)

In [9]:
x.grad

array([[ 2., 10., 12.],
       [ 4., 20., 24.]], dtype=float32)

In [10]:
y.grad

array(-72., dtype=float32)

In [11]:
w1.grad

array([[-22., -16.,  46.]], dtype=float32)

In [12]:
w2.grad

array([[-53., -17.]], dtype=float32)

In [231]:
x = Tensor([[1,2,3]],dtype=np.float32)
w1 = Tensor([[-1,-2],[-3,-4],[0,1]],dtype=np.float32,requires_grad=True)
w2 = Tensor([[10,11]],dtype=np.float32,requires_grad=True)

In [232]:
z = x.dot(w1).dot(w2.T)

In [233]:
z

Tensor([[-147.]],name=dot_<dot_<tensor_0>_<tensor_1>_3>_<T_<tensor_2>_4>_5,grad_fn=<DotBackward0>)

In [234]:
z.backward()

In [235]:
x.grad

In [236]:
w1.grad

array([[10., 11.],
       [20., 22.],
       [30., 33.]], dtype=float32)

In [237]:
w2.grad

array([[-7., -7.]], dtype=float32)

In [240]:
z

Tensor([[-147.]],name=dot_<dot_<tensor_0>_<tensor_1>_3>_<T_<tensor_2>_4>_5,grad_fn=<DotBackward0>)